#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(mktemp gitlab-commit-resource-check.XXXXXX)

cat > "$payload" <&0

sha=$(jq -r '.version.sha // ""' < "$payload")

if [ -z "$sha" ]; then
  echo '[]' >&3
else
  jq -n "[
    { sha: \"$sha\" }
  ]" >&3
fi